version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 4
  identical-code:
    enabled: true
    config:
      threshold: 4
plugins:
  duplication:
    enabled: true
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        python:
          mass_threshold: 32
  radon:
    enabled: true
    config:
      threshold: "B"
  fixme:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
  - "**_test.py"
