engines:
  duplication:
    enabled: true
    exclude_paths:
      - "**_test.py"
    config:
      languages:
        python:
          mass_threshold: 32
  radon:
    enabled: true
    config:
      threshold: "B"
  fixme:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - "**.py"
    - "**.md"
