language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 3.5
    - python: 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
before_install:
  - export CC="gcc-5"
  - export CXX="g++-5"
install:
  - pip install numpy
  - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install torch-scatter
  - pip install torch-sparse
  - pip install torch-cluster
  - pip install torch-spline-conv
  - pip install cython && pip install gdist
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && cd ..
after_success:
  - codecov
notifications:
  email: false
