language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install --quiet http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install --quiet http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install --quiet http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl; fi
  - pip install torchvision
  - pip install -r requirements_test.txt
  - pip install codecov
script:
  - flake8 .
  - nosetests --with-coverage
after_success:
  - codecov
notifications:
  email: false
