package:
  name: pytorch-geometric
  version: 1.7.2

source:
  git_url: https://github.com/rusty1s/pytorch_geometric.git

requirements:
  host:
    - pip
    - python

  run:
    - python
    - pytorch
    - pytorch-scatter
    - pytorch-sparse
    - pytorch-cluster
    - pytorch-spline-conv
    - networkx
    - tqdm
    - jinja2
    - pyparsing
    - scikit-learn
    - python-louvain
    - googledrivedownloader
    - pandas
    - requests
    - numpy

test:
  imports:
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

build:
  noarch: python
  script: pip install .

about:
  home: https://github.com/rusty1s/pytorch_geometric
  license: MIT
  summary: Geometric Deep Learning Extension Library for PyTorch
