name: Examples

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Everyday at 7:00am UTC/11:00pm PST

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        torch-version: [1.11.0]
        include:
          - torch-version: 1.11.0
            torchvision-version: 0.12.0

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install torch==${{ matrix.torch-version}}+cpu torchvision==${{ matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install internal dependencies
        run: |
          pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
          pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

      - name: Install main package
        run: |
          pip install .[benchmark]

      - name: Run GCN on Cora
        run: |
          python examples/gcn.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GAT on Cora
        run: |
          python examples/gat.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GIN on MUTAG
        run: |
          python examples/mutag_gin.py --wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Run GNNExplainer
        run: |
          pip install networkx matplotlib
          python examples/gnn_explainer.py
