name: Full Testing

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # Everyday at 6:00am UTC/10:00pm PST

jobs:

  pytest:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        torch-version: [1.12.0]
        include:
          - torch-version: 1.12.0
            torchvision-version: 0.13.0
        exclude:
          - os: windows-latest  # Complains about CUDA mismatch.
            python-version: '3.7'
          - os: windows-latest  # Complains about missing numpy package.
            python-version: '3.10'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          pip install numpy typing-extensions dataclasses
          pip install torch==${{ matrix.torch-version}}+cpu torchvision==${{ matrix.torchvision-version}}+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install internal dependencies
        run: |
          pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

      - name: Install main package
        run: |
          pip install -e .[full,test]

      - name: Run tests
        run: |
          FULL_TEST=1 pytest --cov --cov-report=xml
        shell:
          bash

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
