name: PR Labeler

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:

  triage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: samspills/assign-pr-to-author@v1.0
        if: github.event_name == 'pull_request'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
